### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by SeekPoint** [DTStack/dt-react-monaco-editor#11]
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting dt-python-parser@0.8.0:
npm ERR! Verification failed while extracting dt-python-parser@0.8.0:
npm ERR! sha512-yxrX83+Z9u9jRY/bQdIDpHsTNTVb4XXXXi+QWYRRgV2DZDXl1wqjmCJNGNfgsHM0ymAJXqx5IkZgA== integrity checksum failed when using sha512: wanted sha512-yxrX83+Z9u9jRY/bQdIDpHsTNTVb4Vg2fvzcgvXjOyi+QWYRRgV2DZDXl1wqjmCXXX0ymAJXqx5IkZgA== but got sha512-P5NX0wtbmSkU12rY5nopwjSB4L7q/54uWKSyXXXXX1W+WRGog4yTn2iy5nYT0ph0XIQGjVc9gNWZGg==. (2030736 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     \Roaming\npm-cache\_logs\2022-08-02T06_25_21_958Z-debug.log
dt-react-monaco-editor>

**Comment by HaydenOrz** [comment]
Please use yarn to install dependencies
