### ISSUE TITLE
Monaco Editor - worker-loader

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-react-monaco-editor#8]
# 升级 Webpack5 
worker-loader 有问题？

**Comment by Smallnuo** [comment]
http://zenpms.dtstack.cn/zentao/story-view-6250.html

**Comment by AndyZjy** [comment]
Python相关语法支持代码中关于报错信息获取的代码没有做非空判断，导致id不存在的时候无限调用worker-loader，进一步导致CPU内存居高不下
